update: random middle letter for each user
infracloudio/spelling-bee pull request #1
Opened 2023-08-18 09:54 UTC by nidhey27

2023-08-18 11:11 UTC, bhavin192 requested changes

2023-08-18 11:11 UTC, bhavin192 commented on src/store.ts
> +      this.middleLetter = selectRandomMiddleLetter(availableLetters); // directly generate random middle letter here
Nice idea! Though we will have problem with this. Because the logic to select a game from allAnswers.json is still based on the date, all of our users will get same game which has fixed possibilities. 

I suggest this approach instead:
1. We modify the generateAnswerObjs to pick any random array element from the allAnswers. 
2. For yesterdaysAnswerObj we can return null.
3. Here in this store.ts file we can comment out the calls to setYesterdaysAnswersAndLastGameDate

Basically, we remove the notion of date from the game. And for every user the whole game will be different, not just the middle letter.

2023-08-18 11:17 UTC, bhavin192 commented on src/components/GameWon.vue
> +  }
This is good for now, we can experiment with copying things from https://github.com/infracloudio/react-wordle/blob/main/src/lib/share.ts later.

2023-08-21 05:58 UTC, nidhey27 commented on src/components/GameWon.vue
> +  }
Yup!

2023-08-24 03:49 UTC, nidhey27 commented on src/store.ts
> +      this.middleLetter = selectRandomMiddleLetter(availableLetters); // directly generate random middle letter here
Reverted!

2023-09-08 07:23 UTC, closed without merging