add: User info modal
infracloudio/spelling-bee pull request #2
Opened 2023-08-22 10:48 UTC by nidhey27

2023-08-24 10:01 UTC, bhavin192 commented on src/App.vue
> +);
```suggestion
const fullName = ref("");
const email = ref("");
const popupModalShown = ref(
  !localStorage.getItem("full_name") || !localStorage.getItem("email")
);

const darkmode = ref(store.theme === "dark");
```

Trying to keep darkmode where it was and adding our lines above it, so when we rebase our changes in future, we don't get any weird conflicts.

2023-08-24 10:01 UTC, bhavin192 commented on src/App.vue
> +
I think these blank lines are added by your IDE. Let's not add these, we will try to keep our changes as minimal as possible.

2023-08-24 10:01 UTC, bhavin192 commented on src/components/GameWon.vue
> +    const response = await axios.post(import.meta.env.VITE_GSA_URL || "", {
Can we import env at top and just do env.VITE_GSA_URL?

2023-08-24 10:01 UTC, bhavin192 commented on src/components/GameWon.vue
> +    console.error('Error sending data:', error);
We should not open the share dialog if there is an error sending the data to the sheet. Can we just return from here?

2023-08-24 12:59 UTC, nidhey27 commented on src/components/GameWon.vue
> +    console.error('Error sending data:', error);
Currently, when user clicks on share button, then we are calling sheet api to store the info. So should we call the api before showing the game won modal? and if the api response is not 200 then we should not show the game won modal?

2023-08-25 08:07 UTC, sahil-lakhwani commented on src/components/GameWon.vue
> +    <p>Well done! You're doing great. Share your score with your friends!</p>
```suggestion
    <p>Well done! You did great. Share your score with your friends!</p>
```

2023-08-25 08:07 UTC, sahil-lakhwani commented on src/components/GameWon.vue
> +      cloud native wordle
shouldn't be wordle I guess?

2023-09-04 07:23 UTC, bhavin192 requested changes

2023-09-04 07:23 UTC, bhavin192 commented on src/components/GameWon.vue
> +  }
Can you try implementing this functionality here?
https://github.com/infracloudio/react-wordle/blob/20a87ecea0098f51fe593ab197d2a1b7587fa43b/src/lib/share.ts#L39-L62

Basically, if navigator.share fails it falls back to copying to clipboard, and shows a text to user stating, the message has been copied to clipboard.

2023-09-04 07:23 UTC, bhavin192 commented on src/components/GameWon.vue
> +    );
This post request takes some time to finish, can we show a spinning ring on the share button when it is pressed, otherwise it is not clear what's going on.

2023-09-04 07:23 UTC, bhavin192 commented on .env
> +VITE_GSA_URL="https://script.google.com/macros/s/AKfycbxee9OQhJV0udREFodBgVHnPMJR8Q_UJpq4j2ATUiBOND7hLA3Z6_ytr1YIWCrxn5z7/exec"
```suggestion
VITE_GSA_URL="https://script.google.com/macros/s/AKfycbyOkg88AKp3R-F68H9R7JWlHvyZaNUfKA82n4Dy117QmXWDItyyPdtM_6FU8paZLoCN/exec"
```

New URL shared by Mohit.

2023-09-07 08:01 UTC, merged